const getAllProvinces = () => {
  return [
    "An Giang",
    "Bà Rịa - Vũng Tàu",
    "Bạc Liêu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bắc Ninh",
    "Bến Tre",
    "Bình Dương",
    "Bình Định",
    "Bình Phước",
    "Bình Thuận",
    "Cà Mau",
    "Cao Bằng",
    "Cần Thơ",
    "Đà Nẵng",
    "Đăk Lăk",
    "Đăk Nông",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Nội",
    "Hà Tĩnh",
    "Hải Dương",
    "Hải Phòng",
    "Hậu Giang",
    "Hòa Bình",
    "Hưng Yên",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Lạng Sơn",
    "Lào Cai",
    "Lâm Đồng",
    "Long An",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Phú Yên",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "TP HCM",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên Huế",
    "Tiền Giang",
    "Trà Vinh",
    "Tuyên Quang",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái",
  ];
};

const getCDCInfo = () => {
  return [
    {
      province: "An Giang",
      hotline: "0853 000 115",
      website: "https://cdcangiang.vn/",
    },
    {
      province: "Bà Rịa - Vũng Tàu",
      hotline: "0962 51 55 77",
      website: "http://soyte.baria-vungtau.gov.vn/",
    },
    {
      province: "Bạc Liêu",
      hotline: "0966 821 919",
      website: "http://ttksbtbaclieu.gov.vn/",
    },
    {
      province: "Bắc Giang",
      hotline: "0204 3852 717",
      website: "http://kiemsoatbenhtatbacgiang.vn/",
    },
    {
      province: "Bắc Kạn",
      hotline: "0209 3870 943",
      website: "http://cdc.backan.gov.vn/",
    },
    {
      province: "Bắc Ninh",
      hotline: "0222 3851 447",
      website: "http://bacninhcdc.vn/",
    },
    {
      province: "Bến Tre",
      hotline: "0868 457 691",
      website: "https://cdcbentre.org/",
    },
    {
      province: "Bình Dương",
      hotline: "0274 382 1785",
      website: "https://ksbtbinhduong.com/",
    },
    {
      province: "Bình Định",
      hotline: "0888 717 559",
      website: "http://kiemsoatbenhtat.syt.binhdinh.gov.vn/",
    },
    {
      province: "Bình Phước",
      hotline: "0918 434 976",
      website: "http://syt.binhphuoc.gov.vn/",
    },
    {
      province: "Bình Thuận",
      hotline: "0252 382 1933",
      website: "https://syt.binhthuan.gov.vn/",
    },
    {
      province: "Cà Mau",
      hotline: "0349 535 657",
      website: "https://soyte.camau.gov.vn/",
    },
    {
      province: "Cao Bằng",
      hotline: "0812 848 389",
      website: "http://cdc.soytecaobang.gov.vn/",
    },
    {
      province: "Cần Thơ",
      hotline: "0292 3822 351",
      website: "https://cdccantho.vn/",
    },
    {
      province: "Đà Nẵng",
      hotline: "0236 382 1469",
      website: "https://ksbtdanang.vn/",
    },
    {
      province: "Đăk Lăk",
      hotline: "0262 384 3770",
      website: "http://yte.daklak.gov.vn/",
    },
    {
      province: "Đăk Nông",
      hotline: "0829 297 578",
      website: "http://syt.daknong.gov.vn/",
    },
    {
      province: "Điện Biên",
      hotline: "02153 827 465",
      website: "http://kiemsoatbenhtatdienbien.vn/",
    },
    {
      province: "Đồng Nai",
      hotline: "02513 897 208",
      website: "http://www.dongnaicdc.vn/",
    },
    {
      province: "Đồng Tháp",
      hotline: "0277 3852 756",
      website: "http://cdcdongthap.gov.vn/",
    },
    {
      province: "Gia Lai",
      hotline: "0269 3824 372",
      website: "http://syt.gialai.gov.vn/",
    },
    {
      province: "Hà Giang",
      hotline: "0219 3886 475",
      website: "http://ytehagiang.org.vn/",
    },
    {
      province: "Hà Nam",
      hotline: "0226 3852 698",
      website: "https://cdchanam.vn/",
    },
    {
      province: "Hà Nội",
      hotline: "1900 3228",
      website: "http://hanoicdc.gov.vn/",
    },
    {
      province: "Hà Tĩnh",
      hotline: "0239 3891 183",
      website: "http://cdc.hatinh.gov.vn/",
    },
    {
      province: "Hải Dương",
      hotline: "0866 028 926",
      website: "http://haiduong.gov.vn/",
    },
    {
      province: "Hải Phòng",
      hotline: "0225 3842 878",
      website: "http://soytehaiphong.gov.vn/",
    },
    {
      province: "Hậu Giang",
      hotline: "02933 878 953",
      website: "http://www.cdchaugiang.org.vn/",
    },
    {
      province: "Hòa Bình",
      hotline: "02183 857 005",
      website: "https://ksbthoabinh.vn/",
    },
    {
      province: "Hưng Yên",
      hotline: "0221 386 4138",
      website: "http://cdchungyen.vn/",
    },
    {
      province: "Khánh Hòa",
      hotline: "0911 66 22 33",
      website: "http://www.ksbtkhanhhoa.vn/",
    },
    {
      province: "Kiên Giang",
      hotline: "0886 86 13 14",
      website: "https://syt.kiengiang.gov.vn/",
    },
    {
      province: "Kon Tum",
      hotline: "02603 505 900",
      website: "https://cdckontum.vn/",
    },
    {
      province: "Lai Châu",
      hotline: "0213 3876 698",
      website: "http://soyte.laichau.gov.vn/ttksbenhtat",
    },
    {
      province: "Lạng Sơn",
      hotline: "0253 812 258",
      website: "https://soyt.langson.gov.vn/",
    },
    {
      province: "Lào Cai",
      hotline: "0214 3844 882",
      website: "https://syt.laocai.gov.vn/",
    },
    {
      province: "Lâm Đồng",
      hotline: "0263 3816 864",
      website: "https://syt.lamdong.gov.vn/",
    },
    {
      province: "Long An",
      hotline: "0723 826 330",
      website: "http://bvdkla.longan.gov.vn/",
    },
    {
      province: "Nam Định",
      hotline: "0393 135 113",
      website: "http://namdinhcdc.com/",
    },
    {
      province: "Nghệ An",
      hotline: "02386 555 666",
      website: "http://www.yte.nghean.gov.vn/",
    },
    {
      province: "Ninh Bình",
      hotline: "0229 3871 137",
      website: "http://cdc.ninhbinh.gov.vn/",
    },
    {
      province: "Ninh Thuận",
      hotline: "0259 382 3368",
      website: "http://www.ninhthuan.gov.vn/",
    },
    {
      province: "Phú Thọ",
      hotline: "1800 9275",
      website: "http://kiemsoatbenhtatphutho.gov.vn/",
    },
    {
      province: "Phú Yên",
      hotline: "0257 381 1167",
      website: "https://soyte.phuyen.gov.vn/",
    },
    {
      province: "Quảng Bình",
      hotline: "0969 871 313",
      website: "http://cdcquangbinh.gov.vn/",
    },
    {
      province: "Quảng Nam",
      hotline: "0913 693 131",
      website: "http://soyte.quangnam.gov.vn/",
    },
    {
      province: "Quảng Ngãi",
      hotline: "0914 021 022",
      website: "https://syt.quangngai.gov.vn/",
    },
    {
      province: "Quảng Ninh",
      hotline: "0203 3825 449",
      website: "http://www.quangninhcdc.vn/",
    },
    {
      province: "Quảng Trị",
      hotline: "0233 3852 583",
      website: "https://cdcquangtri.vn/",
    },
    {
      province: "Sóc Trăng",
      hotline: "0299 3822 576",
      website: "https://soyte.soctrang.gov.vn/",
    },
    {
      province: "Sơn La",
      hotline: "0212 3666 115",
      website: "http://cdcsonla.gov.vn/",
    },
    {
      province: "Tây Ninh",
      hotline: "0276 3822 474",
      website: "http://cdc.ytetayninh.vn/",
    },
    {
      province: "Thái Bình",
      hotline: "02273 831 722",
      website: "http://cdcthaibinh.vn/",
    },
    {
      province: "Thái Nguyên",
      hotline: "0208 3655 504",
      website: "http://soytethainguyen.gov.vn/",
    },
    {
      province: "Thanh Hóa",
      hotline: "0916 803 115",
      website: "http://syt.thanhhoa.gov.vn/",
    },
    {
      province: "Thừa Thiên Huế",
      hotline: "0234 3822 466",
      website: "https://cdc.thuathienhue.gov.vn/",
    },
    {
      province: "Tiền Giang",
      hotline: "0273 387 2368",
      website: "http://trungtamkiemsoatbenhtattiengiang.gov.vn/",
    },
    {
      province: "TP HCM",
      hotline: "08 6957 7133",
      website: "https://hcdc.vn/",
    },
    {
      province: "Trà Vinh",
      hotline: "0239 4862 399",
      website: "http://soytetravinh.gov.vn/",
    },
    {
      province: "Tuyên Quang",
      hotline: "0273 821 057",
      website: "http://soytetuyenquang.gov.vn/",
    },
    {
      province: "Vĩnh Long",
      hotline: "0270 382 2431",
      website: "http://portal.vinhlong.gov.vn/",
    },
    {
      province: "Vĩnh Phúc",
      hotline: "0211 3862 646",
      website: "https://cdcvinhphuc.vn/",
    },
    {
      province: "Yên Bái",
      hotline: "0216 3818 555",
      website: "https://yenbai.gov.vn/covid19/",
    },
  ];
};

export { getAllProvinces, getCDCInfo };
